from PySide6.QtWidgets import QHBoxLayout, QLabel, QProgressBar, QVBoxLayout, QWidget


class StatStrip(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setObjectName("statStrip")
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 2, 0, 4)
        layout.setSpacing(8)
        top = QHBoxLayout()
        self.total = QLabel("0 images")
        self.reviewed = QLabel("0 reviewed")
        self.reviewed.setObjectName("mutedLabel")
        top.addWidget(self.total)
        top.addStretch()
        top.addWidget(self.reviewed)
        layout.addLayout(top)
        self.progress = QProgressBar()
        self.progress.setRange(0, 1)
        self.progress.setValue(0)
        self.progress.setTextVisible(False)
        self.progress.setAccessibleName("Dataset review completion")
        layout.addWidget(self.progress)
        row = QHBoxLayout()
        self.edited = QLabel("0 edited")
        self.edited.setObjectName("mutedLabel")
        self.pending = QLabel("0 pending")
        self.pending.setObjectName("mutedLabel")
        row.addWidget(self.edited)
        row.addStretch()
        row.addWidget(self.pending)
        layout.addLayout(row)

    def update_counts(self, total, reviewed, edited, pending):
        self.total.setText(f"{total} images")
        self.reviewed.setText(f"{reviewed} reviewed")
        self.edited.setText(f"{edited} edited")
        self.pending.setText(f"{pending} pending")
        self.progress.setRange(0, max(total, 1))
        self.progress.setValue(reviewed)
        self.progress.setToolTip(f"{reviewed} of {total} images reviewed")
